import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="policy-page fade-in">
      {/* Header */}
      <div className="policy-header">
        <span className="policy-header-ornament" aria-hidden="true">✦ ✦ ✦</span>
        <h1 className="policy-title">Privacy Policy</h1>
        <p className="policy-date">Last Updated: September 2026</p>
      </div>

      {/* Body */}
      <div className="policy-body">

        <section className="policy-section">
          <h2 className="policy-section-title">1. Information We Collect</h2>
          <p className="policy-text">
            We collect minimal data necessary to provide secure access and processing within the application:
          </p>
          <ul className="policy-list">
            <li>
              <strong>Authentication &amp; Account Data:</strong> When you sign in via Mobile OTP or Google Sign-In,
              we collect your verified mobile phone number, email address, and profile name generated by the authentication provider.
            </li>
            <li>
              <strong>Transaction Information:</strong> When you book a Seva or offer a Kanike, we collect transaction logs,
              billing details, and delivery addresses for Prasadam shipping. We do not collect or store your raw bank details,
              UPI PINs, or credit card numbers. All payments are processed securely through RBI-authorized external third-party
              payment gateways (e.g., Razorpay / Cashfree).
            </li>
            <li>
              <strong>Device Details:</strong> Basic operational indicators (OS version, device model) are processed dynamically
              strictly to send push notifications and fix crash performance logs.
            </li>
          </ul>
        </section>

        <section className="policy-section">
          <h2 className="policy-section-title">2. How We Use Your Information</h2>
          <p className="policy-text">
            Your data is processed strictly for spiritual and administrative utility:
          </p>
          <ul className="policy-list">
            <li>To verify your identity and manage your Devotee Profile.</li>
            <li>To record your Gothra/Name coordinates accurately for performance during the booked Seva rituals.</li>
            <li>To dispatch temple Prasadam via post to your registered physical address.</li>
            <li>To transmit critical Matha updates, festival calendars, and Panchanga announcements via push notifications.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2 className="policy-section-title">3. Data Storage and Security</h2>
          <ul className="policy-list">
            <li>
              Your account credentials, profile details, and ritual records are stored securely using industry-standard
              encrypted servers provided by Supabase / Firebase.
            </li>
            <li>
              We enforce strict access tokens (JWT) to ensure your account remains permanently and safely remembered on your
              device until you choose to explicitly click "Sign Out."
            </li>
          </ul>
        </section>

        <section className="policy-section">
          <h2 className="policy-section-title">4. Third-Party Sharing</h2>
          <ul className="policy-list">
            <li>
              We never sell, trade, or rent devotee data to third-party advertising networks or external data corporations.
            </li>
            <li>
              Data is shared exclusively with critical operational infrastructure partners: payment processors to clear Seva
              payments and postal/courier agencies to ship Prasadam.
            </li>
          </ul>
        </section>

        <section className="policy-section">
          <h2 className="policy-section-title">5. Your Rights and Data Deletion</h2>
          <ul className="policy-list">
            <li>
              Devotees maintain absolute control over their profiles. You can review or edit your address and profile details
              at any time inside the Devotee Details Workspace in the app.
            </li>
            <li>
              If you wish to permanently purge your account records from the Matha database, you can submit an official request
              to the Matha Administration Office, and your profile data row will be completely deleted within the standard legal window.
            </li>
          </ul>
        </section>

      </div>
    </div>
  );
};

export default PrivacyPolicy;
